# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

   config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.synced_folder "C:/vagrant/sf__legacy_vagrant/empty_file.txt", "/home/vagrant/empty_file.txt"

  config.vm.provision "shell", inline: <<-SHELL
    echo "Обновление системы..."
    apt-get update -y

    echo "Установка Python3 и pip..."
    apt-get install -y python3 python3-pip

    echo "Установка библиотек psycopg2 и Django..."
    pip3 install psycopg2 Django
  SHELL
end

